baseURL = 'https://albertoreineri.it/'
defaultContentLanguage = 'it'
title = 'Alberto Reineri'
theme = 'alberto-reineri'

[languages.it]
  label = 'Italiano'
  locale = 'it-IT'
  weight = 1

[params]
  description = 'Alberto Reineri — Web design, sviluppo e infrastruttura web.'
  formspreeEndpoint = 'https://formspree.io/f/mlgkavgo'
  googleAnalyticsId = 'G-9MQ20QPDEM'

[permalinks]
  blog = "/:contentbasename/"

[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 2
  endLevel = 3
  ordered = false
